### ISSUE TITLE
Missing operator when using PyTorch Lightning

### ISSUE THREAD

**Issue by mlnmk** [intel/neural-compressor#1005]
Hi everyone,

I've got the following issue when trying to quantize a PyTorch Lightning object detection model (based on the yolo architecture):
`NotImplementedError: Could not run 'aten::cat.out' with arguments from the 'QuantizedCUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::cat.out' is only available for these backends: [CPU, CUDA, Meta, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].`

It happens when I use CUDA during the testing phase, once the quantization is done. I also tried to run Intel Neural Compressor with the CPU but this time my mean average precision is not computed (really strange since the code doesn't even go in the evaluation function.

Thanks in advance for any help!

**Comment by xin3he** [comment]
Hi @mlnmk The error is because that you are trying to pass a quantized tensor to a non-quantized kernel. It comes from the gap of int8 kernel set between CPU and GPU. Therefore, it's recommended to use CPU for both quantization and inference. As for your precision issue, I cannot provide suggestions without more details. Thanks.

**Comment by chensuyue** [comment]
Close the ticket since no further feedback, please feel free to re-open if you still have the same issue.
