### ISSUE TITLE
torchvision quantization.resnet18 model do not dequantized maxpool

### ISSUE THREAD

**Issue by fireinice** [intel/neural-compressor#1006]
Hi, all
I use neural-compressor to try to quant resnet18 model import from torchvision.models.quantization.resnet18. and when i try to eval the quant model, it always throw exception:
```
Traceback (most recent call last):  File "/root/micromamba/envs/circuit/lib/python3.9/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]  File "/root/micromamba/envs/circuit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl    return forward_call(*input, **kwargs)
  File "<eval_with_key>.188", line 13, in forward
    add = dequantize_4 + maxpool;  dequantize_4 = maxpool = NoneRuntimeError: promoteTypes with quantized numbers is not handled yet; figure out what the correct rules should be, offending types: Float QUInt8
Call using an FX-traced Module, line 13 of the traced Module's generated forward function:
    dequantize_4 = layer1_0_conv2.dequantize();  layer1_0_conv2 = None    add = dequantize_4 + maxpool;  dequantize_4 = maxpool = None
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    layer1_0_relu_1 = getattr(self.layer1, "0").relu(add);  add = None    layer1_1_conv1_input_scale_0 = self.layer1_1_conv1_input_scale_0
```
I guess it indicated  the fx do not dequant the maxpool of the model and try to add a uint8 var (maxpool) with a fp32 var （dequantize_4)?

I try to use the op_type_dict with { 'maxpool': FP32} but no lucky.

Any ideas ? thanks.

I use conda to build environmet:
```
pytorch                   1.12.1          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-lightning         1.7.7                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
torchvision               0.13.1               py39_cu113    pytorch
neural-compressor         2.1.1                      py_0    intel
```

I also tried to use the xpu version of pytorch from channel intel, no lucky either.

**Comment by violetch24** [comment]
Hi,

With the same environment you provided, I was not able to reproduce this issue using INC's [example](https://github.com/intel/neural-compressor/tree/master/examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/fx). Could you share more details like the script and command you used so I can better look into it? Thanks!

**Comment by chensuyue** [comment]
Closed the issue due to no update for a long time, please re-open the ticket if the issue still there.
