### ISSUE TITLE
Auto folding selection for SQ

### ISSUE THREAD

**Issue by maktukmak** [intel/neural-compressor#1041]
While doing smoothquant, INC has the option of using absorb layers or mul ops inserting via folding flag. When folding is True, absorb layers are used if they exist before the quantization layer. If not, smoothquant is skipped for that layer. When folding is False, smoothquant is applied to every layer by inserting mul ops before the quantization layers. 

In the current case, there is no complete solution, i.e., either we lose the performance when we insert mul ops when folding is False, or we lose the accuracy due to non-existing absorb layers when folding is True.

A better solution would be to use absorbing layers whenever they exist, and inserting mul ops for the rest of the quantization layers automatically. So, I suggest adding folding=auto option for this.  

If there is no such work in progress, you can assign this task to me so that I can try to implement it.

**Comment by xin3he** [comment]
Hi @maktukmak , It's true that we don't have this plan. IPEX will help fuse the mul into previous operator, so we don't worry about the performance. If you found that any model got worse performance with folding=False comparing with True, you can raise it to us.

**Comment by chensuyue** [comment]
Closed the issue due to no update for a long time, please re-open the ticket if the issue still there.
