### ISSUE TITLE
Detailed information about sparsity algorithm?

### ISSUE THREAD

**Issue by wenjingk-xilinx** [intel/neural-compressor#108]
@airMeng 
Hi, can you provide some more detailed information about the sparsity method on this [page ](https://github.com/intel/neural-compressor/blob/master/docs/sparsity.md)? what does the sparsity pattern mean? (ex, 2x1, 16x4 )

**Comment by airMeng** [comment]
Hi wenjingk, we prefer tile-wise sparsity in INC, which is balance between accuracy and performance. Tile-wise sparsity means to divide the whole matrix into tiles, if there are non-zero elements in the tile, the tile is called non-zero tiles. the ```2x1```, ```16x4``` corresponds to shapes of tile, like ```2x1``` means the tile is in ```2x1```shape,  and the below image demonstrates so-called ```4x1```
![image](https://user-images.githubusercontent.com/39229107/187156917-dd74d55e-7208-4ee7-adb8-3ee4976649c8.png)

For more details like why we choose ```2x1```, you can refer to some of my [gist](https://gist.github.com/airMeng/7b1a36cfdeee91b219de4357518d14e4), not totally the same but similar. We will give more details soon, and feel free to raise any issues!

cc @ftian1 @XinyuYe-Intel

**Comment by chensuyue** [comment]
Closed due to no further question.
