### ISSUE TITLE
Sparsity mentioned as 0 in inc_config.json even though I am passting sparsity as 0.5 in pruning_config. 

### ISSUE THREAD

**Issue by hardikkamboj** [intel/neural-compressor#1088]
I am currently trying pruning whisper medium mode, I am passing this as the pruning config, object of `WeightPruningConfig`. 
```
pruning_config = WeightPruningConfig(
                            pruning_type="snip_momentum" ,
                            sparsity_decay_type = "exp",
                            max_sparsity_ratio_per_op=0.98,
                            start_step=0,
                            end_step=1000,
                            target_sparsity=0.5,
                            pruning_scope="local")
                       
```
Even though I have mentioned target_sparsity as 0.5, I am getting sparsity = 0.0 in the inc_conig.json, saved in the checkpoint folder
```
{
  "distillation":{},
  "neural_compressor_version":"2.1.1",
  "optimum_version":"1.8.6",
  "pruning": {
    "approach":  "snip_momentum",
    "pattern": "4x1",
    "sparsity": 0.0
  },
  "quantization" :{},
  "save_onnx_model": false,
  "torch_version":"1.13.1",
  "transformers_version": "4.29.2"
}
```
Is there something wrong in my approach, or the config file is showing the wrong numbers, how can I verify that my model is pruned?

**Comment by YIYANGCAI** [comment]
Thanks for bring up this issue. Could you check the sparsity info log during the pruning process? (I mean the logger outputs during training, rather than the final summary log of inc_config.json)

**Comment by chensuyue** [comment]
Closed the issue due to no update for a long time, please re-open the ticket if the issue still there.
