### ISSUE TITLE
Which version of onnx-tool is suitable？

### ISSUE THREAD

**Issue by yileld** [intel/neural-compressor#1096]
My version of neural-compressor is 2.1 and I tried several versions of onnx-tool when quantize model but all not work, and different onnx-tool comes out different error. 
So is there any list of the version of onnx-tool and neural-compressor?

**Comment by mengniwang95** [comment]
Could you share some onnx-tool you used and their error infos?

**Comment by chensuyue** [comment]
Closed the issue due to no update for a long time, please re-open the ticket if the issue still there.
