### ISSUE TITLE
Failed to run demo case

### ISSUE THREAD

**Issue by trajepl** [intel/neural-compressor#114]
When run the demo case in `README`, I met following issues:

### UNIMPLEMENTED: DNN library is not found:
![image](https://user-images.githubusercontent.com/13343117/191494218-29a567f3-1332-4f69-9218-745b2b1fcc04.png)

### Please install Intel® Optimizations for TensorFlow or MKL enabled TensorFlow from source code within version >=1.14.0 and <=2.1
![image](https://user-images.githubusercontent.com/13343117/191494463-c84b070c-3049-4dbd-94dd-e7632d5b4804.png)

All the above errors were caused by wrong tensorflow version which can be fixed by:
``` sh
pip install tensorflow==2.8.2
pip install intel-tensorflow==2.9.1
```
![image](https://user-images.githubusercontent.com/13343117/191494854-52955d36-8015-4541-896d-42702e51d181.png)

I am not sure if it is the right way to set up the tensorflow envs or is there any elegant way to run the demo case?

**Comment by chensuyue** [comment]
Yes, that's the right way to setup tensorflow env by 'pip install intel-tensorflow', and we recommend to use the verified TF versions here https://github.com/intel/neural-compressor#validated-software-environment. Which demo did you run? I can double check the readme.

**Comment by trajepl** [comment]
Thanks~ :)

This demo in the homepage of this repo:
![image](https://user-images.githubusercontent.com/13343117/197941804-a3a78462-9370-458d-b756-4456f0fbec43.png)
