### ISSUE TITLE
GPU support for Quantisation Aware Training (QAT)

### ISSUE THREAD

**Issue by georgesterpu** [intel/neural-compressor#1147]
Hello,

When setting up the QAT Config with the `device="gpu"` argument, the [initialisation code in Pytorch_FXAdaptor](https://github.com/intel/neural-compressor/blob/master/neural_compressor/adaptor/pytorch.py#L3270) returns the following assertion error: `Unsupported this device gpu`.  It looks like only a `cpu` device is supported. However, the `PytorchAdaptor` class does seem to support [both CPU and GPU devices](https://github.com/intel/neural-compressor/blob/master/neural_compressor/adaptor/pytorch.py#L1488), but it is not clear how to enable it from the QAT config, since the `default` backend falls back to `pytorch_fx` instead of `pytorch`.

Could you please let me know if QAT is fully supported on GPU devices?

Thank you.

**Comment by xin3he** [comment]
It’s not, we only support cpu in quantization. The int8 model from GPU is different from CPU.
However, you can leverage GPU while training but need to set the device back when convert.
 
                # set CPU
                conf = QuantizationAwareTrainingConfig()
                compression_manager = prepare_compression(model, conf)
                compression_manager.callbacks.on_train_begin()
                model = compression_manager.model
                # set GPU
                q_model = train_func(model)
                # set CPU
                compression_manager.callbacks.on_train_end()
                compression_manager.save("./saved")

**Comment by georgesterpu** [comment]
Thanks @xin3he
