### ISSUE TITLE
Getting error while running deeplab segmentation model.

### ISSUE THREAD

**Issue by ChiragNayak7007** [intel/neural-compressor#118]
I am try to run the deeplab segmentation model in Directory “neural-compressor/examples/tensorflow/semantic_image_segmentation/deeplab/quantization/ptq/main.py”
Data is preferred correctly, which is in form of .tfrecords.
But after preferring steps when I am trying to run the main.py I am getting error.
Raise valueerror(‘found no files in –root matching: {}’.format(glob_pattern))
ValueError: found no files in –root matching: quantization/ptq/datasets/pascal_voc_seg/tfrecord/val-*
 
I have given address of tfrecord folder in yaml file.

**Comment by zehao-intel** [comment]
Hi，

I run the model, and doesn't meet the same error.
Could you double check your dataset and yaml?
My tfrecord file is like this:
![image](https://user-images.githubusercontent.com/86036206/197733744-1c81391f-3701-4056-929a-33d5eefda2b8.png)
And in my yaml, for "root" field under the "dataset", I use: /home/zehaohua/oob/benchmark/frameworks.ai.lpot.intel-lpot/examples/tensorflow/semantic_image_segmentation/deeplab/quantization/ptq/datasets/pascal_voc_seg/tfrecord/
