### ISSUE TITLE
Support for low bit-width Quantization in Intel neural-compressor

### ISSUE THREAD

**Issue by hachons** [intel/neural-compressor#1189]
I'm interested in knowing if Intel neural-compressor currently supports post training quantization for 2-bit and 4-bit models. Could you confirm the same for mixed precision as well? Additionally, I'd appreciate insights on accuracy metrics and any potential challenges associated with achieving accurate inference at such low bit-widths.

**Comment by hshen14** [comment]
Thanks for your interests! I am assuming you are talking about weight-only quantization for 2-bit and 4-bit (if not, please correct me). We provided such support: https://github.com/intel/neural-compressor/blob/master/docs/source/quantization_weight_only.md. Please note that 4-bit is relatively more mature than 2-bit in terms of quantization recipe. The accuracy metric depends on the task/dataset, and multiple factors may impact the accuracy. Please elaborate more regarding your request (e.g., model/dataset/metric). Thanks.
