### ISSUE TITLE
 neural-compressor can't quantize onnx.ModelProto exceeds maximum protobuf size of 2GB

### ISSUE THREAD

**Issue by rnwang04** [intel/neural-compressor#120]
When I use  neural-compressor to quantize some large model, which corresponding onnx.ModelProto exceeds maximum protobuf size of 2GB, quantization will fail in several parts which include ”ort.InferenceSession(model.SerializeToString(), so)“, below are examples:
![image](https://user-images.githubusercontent.com/105281011/197393118-c3fdaacf-af75-4de1-b85e-a0abd4ab2d89.png)
![image](https://user-images.githubusercontent.com/105281011/197393126-ed940764-bcef-4149-953c-2e609c938c29.png)

Do you consider this problem could be fixed within neural-compressor using some operation like replacing model.SerializeToString() with str or something else?

Thanks!

**Comment by mengniwang95** [comment]
Hi @rnwang04 , thank you for reporting this issue, we are fixing this problem internally. I will let you known as soon as it is merged, and then you can try the nightly version.

**Comment by rnwang04** [comment]
Glad to hear this and hope to get some latest updates ASAP : )

**Comment by mengniwang95** [comment]
hi @rnwang04 , fixing for this issue has been merged internally, you can try the nightly version tomorrow.

**Comment by rnwang04** [comment]
hi @mengniwang95  thanks for this fix ! But I wonder how can I install the nightly version ?
When I try pip install --pre --upgrade, I  got the 1.14.2 version.

**Comment by mengniwang95** [comment]
please refer this section https://github.com/intel/neural-compressor#install-on-linux
