### ISSUE TITLE
can not conduct per-tensor quantisation? 

### ISSUE THREAD

**Issue by Mingxiao-Li** [intel/neural-compressor#127]
Hi 
below is my config file:

version: 1.0

model:
  name: bert
  framework: pytorch                                 # Mandatory: possible values are pytorch and pytorch_fx.

device: cpu

quantization:
  approach: quant_aware_training             # Mandatory: Quantization approach, default to dynamic quantization.
  model_wise:
    weight:
      granularity: per_tensor
      dtype: int8

tuning:
  accuracy_criterion:
    relative: 0.05                                   # Optional. default value is relative, can also be set to absolute. this example allows relative accuracy loss: 5%.
  exit_policy:
    timeout: 0                                       # Optional: tuning timeout (seconds). default value is 0 which means early stop. combine with max_trials field to decide when to exit.
    max_trials: 4
  random_seed: 9527  

The "best_configure" in the weights of output model shows that the weights of the model is still quantized using per-channel.  I am wondering what the per-tensor setting in the config doesn't work ?

**Comment by xin3he** [comment]
Our design disables per-tensor weight selection to avoid exponential growth of the search space. You can check the file `neural_compressor/adaptor/pytorch_cpu.yaml` to add it back.
We haven't decided whether to add it or not. You will be notified if there are any updates.

**Comment by Mingxiao-Li** [comment]
> Our design disables per-tensor weight selection to avoid exponential growth of the search space. You can check the file `neural_compressor/adaptor/pytorch_cpu.yaml` to add it back if needed. The best recommended quantization configs are still under evaluation, and will be reflected in `neural_compressor/adaptor/pytorch_cpu.yaml`.

Hi, thanks for the answers. I checked the pytorch_cpu.yaml file, but I still don't understand what do you mean by adding it back ? Do you mean I want to train a model with per-tensor quantization I just need to change all "per-channel" to "per-tensor" in the pytorch_cpu.yaml file ?

**Comment by xin3he** [comment]
Yes, it should work.

**Comment by hshen14** [comment]
> > Our design disables per-tensor weight selection to avoid exponential growth of the search space. You can check the file `neural_compressor/adaptor/pytorch_cpu.yaml` to add it back if needed. The best recommended quantization configs are still under evaluation, and will be reflected in `neural_compressor/adaptor/pytorch_cpu.yaml`.
> 
> Hi, thanks for the answers. I checked the pytorch_cpu.yaml file, but I still don't understand what do you mean by adding it back ? Do you mean I want to train a model with per-tensor quantization I just need to change all "per-channel" to "per-tensor" in the pytorch_cpu.yaml file ?

"Adding back' means that we may update the pytorch_cpu.yaml to allow both per-tensor and per-channel. Typically, frameworkname_xyz.yaml defines the quantization capabilities that guide the quantization config tuning mainly for post-training quantization. You can try changing pytorch_cpu.yaml as a temp solution and see whether it works for you. We plan to enhance the checker if user specified value has potential conflict with the one defined by framework yaml. Thanks again for reporting the issue.

**Comment by chensuyue** [comment]
@Mingxiao-Li Can we close this issue?

**Comment by Mingxiao-Li** [comment]
> @Mingxiao-Li Can we close this issue?

Yes, many thanks.
