### ISSUE TITLE
Evaluate quantized tensorflow model

### ISSUE THREAD

**Issue by paguilomanas** [intel/neural-compressor#1332]
I have been trying to quantize a TensorFlow model and using it for inferencing. However, although quantization seems to be working I am unable to call the model. I have tried using both formats (TensorFlow saved model and keras .h5) as original fp32 model. It is a VGG16 pretrained model adapted for my dataset and finetuned.

When using the keras model:

`model_path_h5 = "path/to/my/best_VGG16_tf.h5"`

```
from neural_compressor import quantization
from neural_compressor.config import PostTrainingQuantConfig

q_model = quantization.fit(
    model=model_path_h5,
    conf = PostTrainingQuantConfig(backend='itex'),
    calib_dataloader=val_loader) 
```
```
#Inside my inference loop
...
result = q_model(images)
...
```

I can see `q_model` is of type: <neural_compressor.model.keras_model.KerasModel at 0x7fcdf265f490>

And I receive the following error: 

`TypeError: 'KerasModel' object is not callable`

When trying to use the saved model format the quantized model results in the same type of object same error comes up when trying to call it.

Does anyone know how to use the model for evaluation without calling it as I did? Any specific method of the class?

I have tried several other workarounds (not using 'ipex' backend, using `q_model.model ` for inferencing) but all of them result in objects that, in spite of being different from KerasModel, they are always not callable.  

I have also tried to save the object and load it again but it does not seem to work either.

If someone could give me an inference example with quantized tf/keras model it would be of great help (the provided examples in the documentation use a benchmark function which does not clarify much how to use the quantized model).

Let me know if there is any additional information I can provide which may help to solve the issue.

**Comment by zehao-intel** [comment]
Hi @paguilomanas ,

Could you try `model.predict()` API for this Keras model?
Since `q_model` is an object of INC inner class , please use `model = q_model.model` to get `tf.keras.Model` object first.
For reference, we also have VGG16 [example](https://github.com/intel/neural-compressor/tree/master/examples/keras/image_recognition/vgg16/quantization/ptq).
