### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [intel/neural-compressor#1360]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/intel/neural-compressor/assets/147402107/80a0e7ba-4b6b-4602-aaa9-169ba9666884)

**Comment by Kalyanimhala** [comment]
@chensuyue Kindly assign me this issue, I want to work on it.

**Comment by chensuyue** [comment]
Thanks for your comments.  
But the Contributors list already in the right side of the name page, I think that's the common place for it. 

![image](https://github.com/intel/neural-compressor/assets/51692656/3cbe2815-a957-4ea8-bb95-374b98eeef5a)
