### ISSUE TITLE
ZeroQuant Layer Knowledge Distillation (LKD)

### ISSUE THREAD

**Issue by MatteoPagliani** [intel/neural-compressor#1364]
Hi, 
does this example (https://github.com/intel/neural-compressor/blob/master/examples/pytorch/nlp/huggingface_models/text-classification/optimization_pipeline/distillation_for_quantization/fx/run_glue_no_trainer.py) implement Layer Knowledge Distillation (LKD) algorithm proposed by ZeroQuant paper? Link to the paper: https://arxiv.org/abs/2206.01861. Thanks.

**Comment by XinyuYe-Intel** [comment]
Hi @MatteoPagliani ,
No, it isn't. As you can see in the distillation doc, [Intermediate Layer Knowledge Distillation](https://github.com/intel/neural-compressor/blob/master/docs/source/distillation.md#intermediate-layer-knowledge-distillation) is not from ZeroQuant paper, but this example's idea is quite similar to ZeroQuant, though there are some differences.

**Comment by MatteoPagliani** [comment]
Thanks for the answer @XinyuYe-Intel. I've been misled by this readme (https://github.com/intel/neural-compressor/blob/master/examples/pytorch/nlp/huggingface_models/text-classification/optimization_pipeline/distillation_for_quantization/fx/README.md) which states that the algorithm is taken from ZeroQuant paper.
Do you think it would be possible to implement LKD from ZeroQuant paper with your current API?

**Comment by XinyuYe-Intel** [comment]
Idea of distillation for quantization algorithm in this example does originate from ZeroQuant paper, though we made some changes so that our implementation is different with ZeroQuant. 
I think current API cannot support LKD in ZeroQuant.

**Comment by MatteoPagliani** [comment]
Thanks @XinyuYe-Intel !
