### ISSUE TITLE
Slow inference with quantized models

### ISSUE THREAD

**Issue by apdulahyayik** [intel/neural-compressor#1385]
I have quantized a transformer model with the following code:

```py
 model_original = (
        LayoutLMv2ForTokenClassification.from_pretrained(
           "microsoft/layoutxlm-base",
            id2label=id2label,
            label2id=label2id,
        )
    ) 

tuning_criterion = TuningCriterion(max_trials=max_trial)
conf = PostTrainingQuantConfig(approach="static", tuning_criterion=tuning_criterion)  # type: ignore
model_quantised = fit(
    model_original,
    conf=conf,
    calib_dataloader=eval_dataloader,
    eval_func=_eval_func,
)
model_quantised.save(output_folder)
```

Tuning based on the provided `eval_dataloader` is done and at the 13th trial, following INT8 conversions are done.

2023-11-10 20:54:24 [INFO] |*********Mixed Precision Statistics********|
2023-11-10 20:54:24 [INFO] +---------------------+-------+------+------+
2023-11-10 20:54:24 [INFO] |       Op Type       | Total | INT8 | FP32 |
2023-11-10 20:54:24 [INFO] +---------------------+-------+------+------+
2023-11-10 20:54:24 [INFO] |      Embedding      |   7   |  7   |  0   |
2023-11-10 20:54:24 [INFO] |      LayerNorm      |   26  |  0   |  26  |
2023-11-10 20:54:24 [INFO] | quantize_per_tensor |   59  |  59  |  0   |
2023-11-10 20:54:24 [INFO] |        Linear       |   75  |  59  |  16  |
2023-11-10 20:54:24 [INFO] |      dequantize     |   59  |  59  |  0   |
2023-11-10 20:54:24 [INFO] |     input_tensor    |   16  |  16  |  0   |
2023-11-10 20:54:24 [INFO] |       Dropout       |   24  |  0   |  24  |

In the `output_folder`, `best_model.pt` is saved as expected. 

Then, to evaluate the model performance, loaded the model like this

```py
model_original = (
        LayoutLMv2ForTokenClassification.from_pretrained(
           "microsoft/layoutxlm-base",
            id2label=id2label,
            label2id=label2id,
        )
    ) 
 model_quantized =  load(output_folder, model_original) 
```

However `model_quantised` is slower than `model_original` at CPU.
I could not find the problem, after successfull quantization I expect  at least ~3X speed improvement, but it is unfortunately not the case,

I am also sharing `lscpu` output below. Your support is appreciated.

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  2
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:            7
CPU MHz:             3104.894
BogoMIPS:            4999.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-15

**Comment by xin3he** [comment]
Hi @apdulahyayik  It may because of the bad optimization of torch on multi cores. The int8 model cannot leverage all compute resource. Maybe you can observe the perf benefit with command below to limit core number to 4.
```bash
OMP_NUM_THREADS=4 numactl -l -C 0-3 python xxx.py
```
If you want better perf on current configuration. I suggest you to use backend='ipex' in PostTrainingQuantConfig.
Hope these can help you~

**Comment by chensuyue** [comment]
Please reopen the issue if you still got it.
