### ISSUE TITLE
Bug in SmoothQuant algoritm

### ISSUE THREAD

**Issue by pavelkochnev** [intel/neural-compressor#1427]
I think there is a bug in [ORTSmoothQuant._get_smooth_scale()](https://github.com/intel/neural-compressor/blob/de385a432acff1bc0384086c8c35b3442b860fc8/neural_compressor/adaptor/ox_utils/smooth_quant.py#L606):

```
def _get_smooth_scale(self, weights, specific_alpha, tensor):
        """Get smooth scale for specific weight.

        Args:
            weights (numpy.ndarray): weight data
            specific_alpha (float): current alpha for this weights
            tensor (str): tensor name
        """
        weights = np.abs(weights.reshape(weights.shape[0], -1))
        weights_max = np.amax(weights, axis=-1)
        input_power = np.power(self.max_vals_per_channel[tensor], specific_alpha)
        weight_power = np.power(weights_max, 1 - specific_alpha)
        scale = np.clip(input_power / weight_power, a_min=1e-5, a_max=None)
        return scale
```

If all elements are equal to zero in at least one of the `weights` channels, at least one element `weights_max` will be equal to zero to.
This leads to the fact that at least one of the elements of `scale` will be `nan` or `inf`. Model weights will be corrupted in this case and model inference are failed.

**Comment by mengniwang95** [comment]
@pavelkochnev Thank you for your advice, we will fix it soon.

**Comment by chensuyue** [comment]
This issue has been fixed, please re-open if you still got a problem.
