### ISSUE TITLE
Is there any tutorial/example on using INC to do QAT based on ONNX Runtime?

### ISSUE THREAD

**Issue by kyrie2to11** [intel/neural-compressor#1476]
As the title says, any suggestions. Thanks!

**Comment by yuwenzho** [comment]
Hi @kyrie2to11, QAT directly on the ONNX Runtime backend is not supported in INC. If you want to obtain a QAT ONNX model, you can try performing QAT using a PyTorch model and then exporting the quantized model to the ONNX format.

Refer to this [link](https://github.com/intel/neural-compressor/blob/master/docs/source/quantization.md#quantization-aware-training-1) for the tutorial of PyTorch QAT.
Refer to this [link](https://github.com/intel/neural-compressor/blob/master/docs/source/export.md#int8-model-export) for the tutotial and example on how to export a quantized PyTorch model to ONNX format.
