### ISSUE TITLE
Will you support Intel Arc?

### ISSUE THREAD

**Issue by nathanodle** [intel/neural-compressor#1508]
I’m curious if you will support Arc, neural compressor would particularly benefit those platforms!  Thanks!

**Comment by chensuyue** [comment]
We support general (WOQ WIP) quantization for Arc based on IPEX and ITEX. 
Here is an example for IPEX: https://github.com/intel/neural-compressor/blob/master/examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/README.md#2-quantization-with-xpu   
Example for ITEX: https://github.com/intel/neural-compressor/blob/master/examples/tensorflow/nlp/bert_base_mrpc/quantization/ptq/README.md#quantizing-the-model-on-intel-gpumandatory-to-install-itex 
https://github.com/intel/neural-compressor/blob/master/examples/tensorflow/nlp/bert_base_mrpc/quantization/ptq/README.md#quantization-config   
Quantization steps are similar to CPU, just some config difference. The complex part is how to setup a XPU working ENV with IPEX/ITEX.
