### ISSUE TITLE
AssertionError: Framework is not detected correctly from model format.

### ISSUE THREAD

**Issue by AnindyaSD** [intel/neural-compressor#1534]
model_path = "/kaggle/input/train-model/"

q_model = fit(
    model=model_path,
    conf=quantization_config,
    dataloader=test_loader,
    framework='pytorch'
)

This is my code and it is showing an error when trying to quantize the model (.safetensors file) in PyTorch framework, signifying framework incompatibility:
**AssertionError: Framework is not detected correctly from model format. This could be caused by unsupported model or inappropriate framework installation.**

My model is trained using PyTorch, and it is a bert-uncased model, trained to my dataset, and saved as model.safetensors along with a config.json file.

![image](https://github.com/intel/neural-compressor/assets/93717247/c891fdd0-0774-4c4c-8da2-c0e63be9c81c)

Any suggestions on this issue will be much appreciated. I am quite new to this model quantization, so it may be a simple issue. Thanks.

**Comment by yiliu30** [comment]
Hi @AnindyaSD, thank you for reporting the issue. Currently, we do not support automatic detection and loading of models in safetensors format. We suggest you load it manually and pass it to the `fit` API. 

Here are some code snippets that may help you.
```python
# I assume that you are using the `safetensors.torch.save_model` API to save the trained model.
from safetensors.torch import load_model
load_model(model, "trained_model.safetensors") # <----- init the model and load the trained model state_dict by yourself
from neural_compressor.quantization import fit
q_model = fit(model=model, conf=quantization_config, dataloader=test_loader)
```

**Comment by AnindyaSD** [comment]
Hello,
Thank you so much for your guidance. I will try this out, as soon as I get
time. All the help is much appreciated.

Thanks and regards,
Anindya.

**Comment by AnindyaSD** [comment]
Hello again,
I have tried what you said in the above comment. Now, as I am running the fit function, I am getting some warnings and some new errors:
**AttributeError: 'NoneType' object has no attribute 'batch_size'
2024-01-12 04:11:57 [ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal. Exit.**

I have loaded the model according to this:
**from safetensors.torch import load_model
load_model(model, "trained_model.safetensors")**

My dataloader is using test_loader, using this snippet:
**tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=20)
test_inputs = tokenizer(list(test_df['x']), padding=True, truncation=True, return_tensors='pt', max_length=128)
test_labels = torch.tensor(np.array(test_df['y']) - 1, dtype=torch.long)
test_dataset = TensorDataset(test_inputs['input_ids'], test_inputs['attention_mask'], test_labels)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)**

Any insight will be much appreciated. Thanks!

**Comment by yiliu30** [comment]
Hi @AnindyaSD, there is a typo in the above code snippets, please replace the `dataloader` with `calib_dataloader`.

```python
# I assume that you are using the `safetensors.torch.save_model` API to save the trained model.
from safetensors.torch import load_model
load_model(model, "trained_model.safetensors") # <----- init the model and load the trained model state_dict by yourself
from neural_compressor.quantization import fit
q_model = fit(
    model=model,
    conf=quantization_config,
    calib_dataloader=test_loader  # <----- use `calib_dataloader` instead of `dataloader`
    )

```

**Comment by AnindyaSD** [comment]
Hello @yiliu30 sir,

Thanks for the update. I just tried using the snippet you sent above, and I am now getting a new error:
**TypeError: list indices must be integers or slices, not tuple
2024-01-12 05:01:17 [ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal. Exit.**
It seems like there might be an issue with how the quantization library is handling the input during calibration. Any advice on this?

Also, my test_loader yield is around 5400 rows. How much is the model limit? I will edit test_loader accordingly.

**Comment by yiliu30** [comment]
Oh, I think the error was caused by the sample generated by the test_loader can not be consumed by the model. `output = model(sample)` failed.
To fix it, we need to prepare the right `calib_dataloader` and validate it on the original model, like:

```python
# step 1. prepare the calib_dataloader
test_loader = ... 
for sample, label in test_loader:
    output = model(sample)
# It worked, proceed to the next step
# step 2. quantize model
from neural_compressor.quantization import fit
...
```
We already enable the quantization for the `bert-base-uncased` model on several tasks. You can refer to the [link](https://github.com/intel/neural-compressor/tree/master/examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx#1-quantization) for details.

**Comment by AnindyaSD** [comment]
Hello @yiliu30 sir,
Thank you so much for the reply. Turns out to be an error on my part in preparing my dataloader for the calib_dataloader argument. I will try to resolve them, and then close the issue.
All the help you have provided is very much appreciated.
Thanks and regards,
Anindya.

**Comment by yiliu30** [comment]
Hi @AnindyaSD, did you solve the dataloader issue? Feel free to contact us if needed.

**Comment by AnindyaSD** [comment]
Hi @yiliu30 sir, sorry for the late response.
I am still working on it. The snippet seems to run without errors, but it does not stop. Maybe, I have to adjust some parameters. I will refer to the documentation, for further help.
I can't thank you enough for all the help you have provided. I am still learning on this subject, so I am a bit slow on these.
I will close this issue as of now. If I run into further trouble, I will open a new issue.
Thanks and Regards,
Anindya.

**Comment by AnindyaSD** [comment]
Thanks for all the help,
Anindya.
