### ISSUE TITLE
how to get smoothed model before do quantization?

### ISSUE THREAD

**Issue by chunniunai220ml** [intel/neural-compressor#1626]
it seems the run_llama2_sq.py L234:  quantization.fit() do smooth_quant and quantize sequentially,  can i get smoothed model(FP32) to save before do quantization? 
if not, can i get best smooth_quant alpha(sq_alpha) by  AutoTuneStrategy()._transfer_alpha(), then , reproduce correspondingly smoothed model?  

the criterion of the best sq_alpha only depends on quantization  results ?

**Comment by yiliu30** [comment]
Hi, @chunniunai220ml. Thanks for your interest in our project. You can get the smoothed model (without quantization) directly.
Here is a demo that uses `TorchSmoothQuant` instead of `fit` API.

https://github.com/intel/neural-compressor/blob/ec91109399cb1bdf34a51dfbddac5628c488ab7e/test/algorithm/test_smooth_quant.py#L595-L615

**Comment by yiliu30** [comment]
> For the criterion of the best `sq_alpha`, it depends on the usages.
1. If you provide a specific alpha list, like `[0.1, 0.5, 0.8]`, the evaluation result of the whole quantization model will serve as the criterion.
2. If you pass the value `auto`, the quantization error of each layer/block will be utilized as the criterion.

Here is the document. https://github.com/intel/neural-compressor/blob/master/docs/source/smooth_quant.md#determining-the-alpha-through-auto-tuning

**Comment by yiliu30** [comment]
Since we haven't heard back in a while, let's close it for now. Don't hesitate to reopen if you require more help. Thank you!

**Comment by chunniunai220ml** [comment]
hi, @yiliu30  , i  tried to do smooth llama2-7b refer your examples as follows,
def main():
    args = parser.parse_args()
    model_path='llama2-7b'
    user_model = LlamaForCausalLM.from_pretrained(model_path, device_map='auto', torch_dtype=torch.bfloat16)
    device='cuda:0'
    tokenizer = LlamaTokenizer.from_pretrained(model_path)
    print("Data type of the model:", user_model.dtype)
    val_data=get_dataloader(tokenizer,args)
    import pdb; pdb.set_trace()
    sq = TorchSmoothQuant(user_model, val_data) 
    sq.transform(alpha='auto', calib_iter=1, folding=True)  #percentile calib
    assert len(sq.absorb_to_layer) == 1 
    ppl_smooth = eval_ppl(user_model, val_data, device, args)
    print(args.seqlen,ppl_smooth)
    model_to_save = (user_model.module if hasattr(user_model, "module") else user_model)
    fpsmoothed_model='llama2_7b_intel_smoothed.pt'
    model_to_save.save_pretrained(fpsmoothed_model)
    tokenizer.save_pretrained(fpsmoothed_model)


but got stuck in sq.transformer(),  is anything wrong? how should i change the above codes? 
![image](https://github.com/intel/neural-compressor/assets/17668109/55c08410-4e22-4099-bcc5-adc365bb6c18)

**Comment by yiliu30** [comment]
Hello @chunniunai220ml , everything looks good at first glance. Could please run it again using the command below and share the log with me.
```bash
LOGLEVEL=DEBUG python save_sq.py
```

If it still doesn't work, kindly try the `alpha` with dedicated value first.
```python
alpha = 0.5
sq.transform(alpha=alpha, calib_iter=1, folding=True)  #percentile calib
```

Btw, there are some refactor for the smooth quant recently. Please use the [latest commit](https://github.com/intel/neural-compressor/commit/24419c9044fe227ea806db370c1a30272d026f8a).

**Comment by chunniunai220ml** [comment]
> Hello @chunniunai220ml , everything looks good at first glance. Could please run it again using the command below and share the log with me.
> 
> ```shell
> LOGLEVEL=DEBUG python save_sq.py
> ```
> 
> If it still doesn't work, kindly try the `alpha` with dedicated value first.
> 
> ```python
> alpha = 0.5
> sq.transform(alpha=alpha, calib_iter=1, folding=True)  #percentile calib
> ```
> 
> Btw, there are some refactor for the smooth quant recently. Please use the [latest commit](https://github.com/intel/neural-compressor/commit/24419c9044fe227ea806db370c1a30272d026f8a).

i git pull the newest code,
LOGLEVEL=DEBUG no more info, because it got stuck as usual,  set alpha=0.5, the same stuck

**Comment by yiliu30** [comment]
>  but a warning , does it matter? 

The `warning` mean that there is a difference between the output of the original model and the model after smooth quant.  

It may caused by the implementation bugs or numerical  errors.  Please refer the code https://github.com/intel/neural-compressor/blob/24419c9044fe227ea806db370c1a30272d026f8a/neural_compressor/adaptor/torch_utils/waq/smooth_quant.py#L503-L511

**Comment by yiliu30** [comment]
>  what's meaning of the debug info?

The debug info is the min/max of max of input. Please refer the code. https://github.com/intel/neural-compressor/blob/24419c9044fe227ea806db370c1a30272d026f8a/neural_compressor/adaptor/torch_utils/waq/utils.py#L286-L291

**Comment by yiliu30** [comment]
> why need to do assert len(sq.absorb_to_layer) == 1 ?

It's for UT, not necessary for your model.

**Comment by yiliu30** [comment]
> by the way, does the code can run in AMD'S GPU?

We are focus on Intel CPUs/GPUs and did not test it on AMD's GPU. But if stock Pytorch supports it effectively, it ought to function.

**Comment by yiliu30** [comment]
> when i set alpha='auto', bug reports: no shape attribute？

Could you share the code snippet for me? It may help me to reproduce this issue.

**Comment by yiliu30** [comment]
I'll include more relevant log details later to enhance the user experience. Thanks for your input.

**Comment by chunniunai220ml** [comment]
> Could you share the code snippet with me? It may help me to reproduce this issue.

sq.transform(alpha='auto', calib_iter=1, folding=True) ， others the same as above code,   accoding to  the desc 'auto tune alpha', the bug can be located in https://github.com/intel/neural-compressor/blob/24419c9044fe227ea806db370c1a30272d026f8a/neural_compressor/adaptor/torch_utils/waq/auto_alpha.py#L546  #1685 
or line 615

**Comment by chunniunai220ml** [comment]
> > but a warning , does it matter?
> 
> The `warning` mean that there is a difference between the output of the original model and the model after smooth quant.
> 
> It may caused by the implementation bugs or numerical errors. Please refer the code
> 
> https://github.com/intel/neural-compressor/blob/24419c9044fe227ea806db370c1a30272d026f8a/neural_compressor/adaptor/torch_utils/waq/smooth_quant.py#L503-L511

wait for solution, if set alpha=0.5, got the warning ,  so do  alpha='auto' by search

**Comment by yiliu30** [comment]
Hello @chunniunai220ml, I tried the llama-2-7b on my end, but I was unable to replicate this issue. Could you share your full code snippet with me? Thanks.

**Comment by chunniunai220ml** [comment]
> Hello @chunniunai220ml, I tried the llama-2-7b on my end, but I was unable to replicate this issue. Could you share your full code snippet with me? Thanks.

```
import numpy as np
import torch
import argparse
from transformers import LlamaForCausalLM, LlamaTokenizer
from torch.utils.data import DataLoader, TensorDataset
from neural_compressor.adaptor.torch_utils.waq import TorchSmoothQuant

def main():
    args = parser.parse_args()
    model_path='weights/llama-2-7b-hf-bf16/'
    user_model = LlamaForCausalLM.from_pretrained(model_path,device_map='auto',torch_dtype=torch.bfloat16,torchscript=True)
    device='cuda:0'
    tokenizer = LlamaTokenizer.from_pretrained(model_path)
    print("Data type of the model:", user_model.dtype)
    val_data=get_dataloader(tokenizer,args) #wikitext2-raw
    # ppl_ori = eval_ppl(user_model, val_data, device, args)
    # print('ori',args.seqlen,ppl_ori) #
    import pdb; pdb.set_trace()
    sq = TorchSmoothQuant(user_model, val_data) 
    sq.transform(alpha='auto', calib_iter=1, folding=True) 
    # assert len(sq.absorb_to_layer) == 1 
    ppl_smooth = eval_ppl(user_model, val_data, device, args)
    print(args.seqlen,ppl_smooth)
    model_to_save = (user_model.module if hasattr(user_model, "module") else user_model)
    fpsmoothed_model='llama2_7b_intel_smoothed.pt'
    model_to_save.save_pretrained(fpsmoothed_model)
    tokenizer.save_pretrained(fpsmoothed_model)
```
my codes run in Nvidia V100

can u share ur test code to me for reference?

**Comment by yiliu30** [comment]
Sure, here is my code:

https://github.com/intel/neural-compressor/blob/912f584dfba6283db2f0a293ec97f0c1a6761b60/examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py#L328-L339

Please replace the `model` with your model name.

https://github.com/intel/neural-compressor/blob/019bc7a1545d08962d65489a47f8af47aa672ef4/examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_sq.sh#L1-L6

**Comment by chunniunai220ml** [comment]
hi, @yiliu30 i git pull the newest codes, and follow ur example codes,  but got error when test llama2-7b:

![image](https://github.com/intel/neural-compressor/assets/17668109/0e7109a9-c473-4ee4-af20-796a522f1064)

and i load model in dtype=torch.bfloat16， while ur example code set user_model.float(), does this cause the warning : 
[WARNING] Mathematical equivelancy of Smoothquant is not preserved. Please kindly report this issue to https://github.com/intel/neural-compressor.

and i use the model "hf-internal-testing/tiny-random-GPTJForCausalLM" in my code, it shows  sorry, could not trace the model, smooth quant is skipped:
![image](https://github.com/intel/neural-compressor/assets/17668109/d6e9a41c-592c-4e26-8971-a046b9deaa78)

**Comment by yiliu30** [comment]
Hi @chunniunai220ml, can you share the `get_dataloader` function with me? I need it to reproduce the issue.

**Comment by chunniunai220ml** [comment]
> Hi @chunniunai220ml, can you share the `get_dataloader` function from your code with me? I need it to reproduce the issue.

```
def get_wiki2_raw_data(data_path, tokenizer, seqlen, seed=0, nsamples=-1):
    random.seed(seed)
    testdata = load_from_disk(data_path)
    tokenized_text = tokenizer("\n".join(testdata['text']), return_tensors='pt')     
    # tokenized_text = tokenizer("\n\n".join(testdata['text']), return_tensors='pt') #for GPTQ Released code
    tokenized_text_len = tokenized_text.input_ids.shape[1]
    
    valenc = []
    for i in tqdm(range(0, tokenized_text_len - seqlen - 1, seqlen)):
        if len(valenc) == nsamples:
            break
        valenc.append(tokenized_text.input_ids[:, i : i + seqlen])
    
    valenc = torch.dstack(valenc).squeeze().permute(1, 0)
    return valenc

def loader(data, batch_size=1, shuffle=False):
    dataset = TensorDataset(data)
    data_loader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)
    return data_loader

def get_dataloader(tokenizer, args):
    args.dataset="wikitext-2-raw-v1"
    mapping = {"wikitext2-raw": "wikitext-2-raw-v1/test"} 
    data_path = args.dataset_path + mapping[args.dataset]
 
    mapping = {"wikitext2-raw": get_wiki2_raw_data}
    load_data = mapping[args.dataset]
    valloader = loader(load_data(data_path, tokenizer, args.seqlen))
    return  valloader
```

**Comment by yiliu30** [comment]
Hi @chunniunai220ml, sorry for the late reply as I was out of office for the holiday. After the smooth process, we will compare the output between of the original model with that of the smoothed model. As the code show:

https://github.com/intel/neural-compressor/blob/40923112e72c564a6065b87afc84a9a64671aa41/neural_compressor/adaptor/torch_utils/waq/smooth_quant.py#L503-L517
But current, only a few sorts of types are supported. We will enhance it later. Thanks.

**Comment by yiliu30** [comment]
Since we haven't heard back in a while, let's close it for now. Feel free to reopen if you need more help. Thank you!
