### ISSUE TITLE
Using Neural Compressor on cloud resources

### ISSUE THREAD

**Issue by rmiller3** [intel/neural-compressor#1678]
I'm trying to use modal.com to leverage neural-compressor to test compressing some larger models.  I need to give it a base container image, which I used from their example code as nvidia/cuda:12.1.1-devel-ubuntu22.04, but I don't have to use that one presumably.

They also have a variety of GPU configurations, I've tried a few but most recently the A10G.  

If I try to load neural compressor, I get an error because it can't determine the number of CPU and Sockets.  

I copied the code from this library that determines that and confirmed it's an x86 architecture so neural compressor uses lscpu to determine the number of sockets but that returns 0.  

Can someone help me figure out how to get it running in a container?  Is there some special base container image I can use or initialization?  
Thanks!

**Comment by yiliu30** [comment]
Hi @rmiller3, we appreciate your interest in our project. Could you share the docker image link. It can help me to reproduce the issue more quickly.

**Comment by rmiller3** [comment]
I'm using modal.com; they have an API called Image.from_registry(...) described here:
https://modal.com/docs/reference/modal.Image
and loosely based on the image in their example:  https://modal.com/docs/examples/vllm_mixtral

image_nvidia_cuda = (
    modal.Image.from_registry("nvidia/cuda:12.1.1-devel-ubuntu22.04", add_python="3.11")
    .pip_install_from_requirements(requirements_txt="src/functions_for_cloud/cloud_requirements.txt")
)

GPU:  Configurable (A10G, A100, T4 or L4)

cloud_requirements.txt:
```
neural-compressor==2.4.1
evaluate==0.4.1
openai==1.13.3
optimum==1.17.1
optimum-intel==1.15.0
pyyaml==6.0.1
transformers==4.38.1
torch==2.2.1
```

I'm open to using other (base) images but I'm not very knowledgable on dockerfiles.

**Comment by yiliu30** [comment]
Hello @rmiller3 , sorry for the delayed response. I tried to run the image on my local, and it works for me. Since I am unable to create container on modal.com, I am unable to test it in your setting. 
We have updated the sockets determine command to `cat /proc/cpuinfo | grep 'physical id' | sort -u | wc -l`. 

Would you kindly give it a try and let me know how it turns out? We expect it return an int number like `1` or `2`. 

If it works, please use the latest neural-compressor by updating the `cloud_requirements.txt` to:
```txt
git+https://github.com/intel/neural-compressor.git
...
```
If it failed, please attach the output of `cat /proc/cpuinfo`, thanks.

**Comment by rmiller3** [comment]
The modal team said the following:  
```
Modal team:  I just looked at that function and reproduced what you mentioned. Modal programs run inside containers that virtualize CPU resources, so some information like the CPU's "physical id" isn't available. We haven't yet tried neural_compressor but it looks like it would be possible to do.

Me:  So the idea is to find a container that provides (or spoofs) CPU information or somehow build a custom container in a way that can do so? (edited) 

Modal team:  Maybe neural_compressor provides an interface that doesn't require looking up information manually. You could provide information manually if that's the case.
```

For your question.  There isn't any text with 'physical id' in the response.   Here's an example processor.

```
b'flags\t\t: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_vnni md_clear arch_capabilities\n'
b'bogomips\t: 2200.21\n'
b'clflush size\t: 64\n'
b'cache_alignment\t: 64\n'
b'address sizes\t: 46 bits physical, 48 bits virtual\n'
b'power management:\n'
b'\n'
```

**Comment by yiliu30** [comment]
Hi @rmiller3, thanks for your feedback. Detecting the number of sockets is primarily for benchmarking purposes, which might not your main concern.  
I have updated the default number of sockets to `1` in this [branch](https://github.com/intel/neural-compressor/tree/detect_sockets). 
Feel free to move forward, and in the meantime, I'll look into the impact within our team or seek a more refined solution for the container later on.

**Comment by rmiller3** [comment]
Thanks for proposing the fix!  It's still broken for two reasons:

1.  Sockets == 0
It doesn't hit the default since
<br>` 
"cat /proc/cpuinfo | grep 'physical id' | sort -u | wc -l"`
<br> 
returns 0
<br>
2.  Cores == NoneType
<br>`cores = psutil.cpu_count(logical=False)`
<br>Can you make a branch that computes the total CPU count (logical and physical)?

Or maybe an alternate constructor that allows the user to pass in whether to use logical CPUs?
Note:  Fixing the sockets would still cause the code to fail do to dividing the NoneType Cores.

**Comment by yiliu30** [comment]
Oh, I see. I update it at this [branch](https://github.com/intel/neural-compressor/tree/detect_sockets) to detect the cores and sockets when needed. Hope it works on your end.
By the way, could you tell me which example and command you're trying to execute?

> allows the user to pass in whether to use logical CPUs?

This is a good ideas, but we need to consider backward compatibility carefully.

**Comment by rmiller3** [comment]
At first glance it looks like it works, but I haven't gotten into any of the lower libraries yet; I need to refactor some stuff.  Thanks a lot!  I'll update this thread if something seems weird.  

I initially wanted to investigate quantization and pruning on text-generative models so not really an example, but something like these:  https://huggingface.co/docs/optimum/en/intel/optimization_inc.  I got them to run on gpt2, but I wanted to try a larger model, perhaps like mosaicml/mpt-7b?  

On a side note, for pruning, is a training dataset required or can models be pruned effectively without supplying additional training datasets?  Is the dataset used to determine where to optimally prune?

**Comment by yiliu30** [comment]
>  perhaps like mosaicml/mpt-7b?

` mosaicml/mpt-7b` is good, but [llama-2-7b](https://github.com/intel/neural-compressor/tree/master/examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm#llama2-7b13b30b) is more popular :).

> On a side note, for pruning, is a training dataset required or can models be pruned effectively without supplying additional training datasets? Is the dataset used to determine where to optimally prune?

Indeed, a training datasets is required for pruning. Typically, pruning process use the dataset to calculate the importance scores of each weights. Weights with lower scores are then pruned. For further information, please consult the [pruning documentation](https://github.com/intel/neural-compressor/blob/master/docs/source/pruning.md).

**Comment by rmiller3** [comment]
Thanks!  I was a bit delayed investigating llama2-7b since my credentials on huggingface weren't working (I finally figured it out --  the API was case-sensitive and I had to capitalize the "l" in llama) but by then I had collected baseline info on the other one.  I'll give it another look though!
