### ISSUE TITLE
Per tensor quantization in smoothquant

### ISSUE THREAD

**Issue by chensterliu** [intel/neural-compressor#1689]
Hello community,
I've tried the smoothquant flow on  an OPT-125m model with the default setting. Unsurprisely the activations are quantized per tensor and weighs are per channel. According to the following table from the SmoothQuant paper I see weights can be also quantized per tensor (smoothquant-O3). Is it possible to apply smoothquant by setting the QuantizeConfig or other stuff? I really aim a per_tensor quantization on both activations and weights due to a limitation of my hardware. Thanks!

![t3](https://github.com/intel/neural-compressor/assets/32708663/877d9e92-9f25-4c0e-a9b5-3546d724822a)

**Comment by yintong-lu** [comment]
Hi Chen, thanks for your response.
Currently weights could only be quantized per-channel in INC SmoothQuant. Please refer to [SmoothQuant_doc](https://github.com/intel/neural-compressor/blob/master/docs/source/smooth_quant.md) for more details of our implementation.
Thanks!

**Comment by chensterliu** [comment]
I see, thanks for your reply!
