### ISSUE TITLE
NotImplementedError is raised in static INT8 Quantization with PT2E Backend default recipe

### ISSUE THREAD

**Issue by haitamhawa** [intel/neural-compressor#1984]
**Following example from neural-compressor/docs/source/3x/PT_StaticQuant.md:**

I get a crash in `MinMaxObserver` when calling `prepare(model)`: 
"NotImplementedError: MinMaxObserver's qscheme only support torch.per_tensor_symmetric and torch.per_tensor_affine."
The scheme requested prior to error is `per_channel_symmetric`.

i am using default `StaticQuantConfig`.
##
*i think that `per_channel_symmetric` quantization is done on weights only.
And by using `minmax` algorithm, its simply absolute max for each channel, i'm not sure why observer was used in this case.*
##
Environment:
- Linux Ubuntu 22.04.1 LTS
- Python 3.10
- torch 2.4.0+cpu
- neural_compressor 3.0

To reproduce:
```python
import torch
from torch import nn
from neural_compressor.torch.export import export
from neural_compressor.torch.quantization import StaticQuantConfig, prepare, convert

def main():
    # Prepare the float model and example inputs for export model
    model = nn.Linear(5,5)
    example_inputs = (torch.rand(size=(1,5)),)


    # Export eager model into FX graph model
    exported_model = export(model=model, example_inputs=example_inputs)
    # Quantize the model
    quant_config = StaticQuantConfig()
    prepared_model = prepare(exported_model, quant_config=quant_config)
    # Calibrate
    for _ in range(100):
        prepared_model(torch.rand_like(example_inputs[0]))

    q_model = convert(prepared_model)
    # Compile the quantized model and replace the Q/DQ pattern with Q-operator
    from torch._inductor import config

    config.freezing = True
    opt_model = torch.compile(q_model)

if __name__=="__main__":
    main()
```

**Comment by yiliu30** [comment]
Hi @haitamhawa, thanks for raising this issue. Could you try to set `w_granularity` to `per_tensor`? 

```
from neural_compressor.torch.quantization import get_default_static_config, StaticQuantConfig
quant_config = get_default_static_config()
# or 
quant_config  = StaticQuantConfig(w_granularity="per_tensor")
```

**Comment by haitamhawa** [comment]
It did work
But the weights now are quantized per tensor, which might cause high accuracy degradation.
Are you planning to support `per_channel` quantization for weights only?

**Comment by yiliu30** [comment]
> It did work But the weights now are quantized per tensor, which might cause high accuracy degradation. Are you planning to support `per_channel` quantization for weights only?

For weight only, it already supports the `per_channel`  quantization, for example, you can quantize the model with RTN with `per_channel`.

```bash
quant_config = RTNConfig(group_size=-1)
```
Model details can be found here. https://github.com/intel/neural-compressor/blob/master/docs/source/3x/PT_WeightOnlyQuant.md#common-arguments

**Comment by haitamhawa** [comment]
Sorry for the miss-understanding
i mean:
1) Weights are quantized symmetrically `per_channel`
2) Activation are quantized asymmetrically `per_tensor`

as in the default recipe of `StaticQuantConfig`
```
w_dtype: str = "int8",
w_sym: bool = True,
w_granularity: str = "per_channel",
w_algo: str = "minmax",
act_dtype: str = "uint8",
act_sym: bool = False,
act_granularity: str = "per_tensor",
act_algo: str = "minmax"
```

**Comment by yiliu30** [comment]
Oh, I see that PyTorch supports the [PerChannelMinMaxObserver](https://pytorch.org/docs/stable/generated/torch.ao.quantization.observer.PerChannelMinMaxObserver.html#perchannelminmaxobserver). I've added support for it on the [pt2e_per_channel](https://github.com/intel/neural-compressor/tree/pt2e_per_channel)  branch. Please try it again.

https://github.com/intel/neural-compressor/blob/6ec6178a35c0a48f9847e7a915d2cc9fa91cf822/test/3x/torch/quantization/test_pt2e_quant.py#L100-L126

**Comment by yiliu30** [comment]
> [PerChannelMinMaxObserver](https://pytorch.org/docs/stable/generated/torch.ao.quantization.observer.PerChannelMinMaxObserver.html#perchannelminmaxobserver)

Sure, I created a PR for it, I will merge it after some tests.

https://github.com/intel/neural-compressor/pull/1990
