### ISSUE TITLE
Exporting a TF model to an LPOT-supported INT8 representation

### ISSUE THREAD

**Issue by lzrvch** [intel/neural-compressor#2]
Hi,

I have the following question - if I have my custom model trained with TensorFlow Quantization-Aware Training, how can I then export it to a INT8 representation that can be run with LPOT?

Thanks!

**Comment by ftian1** [comment]
sorry for late response due to Chinese new year. 

Currently QAT only enabled at pytorch. Tensorflow QAT support is WIP. When it's ready, there would have a utility func to help convert QAT model to TFDO model. (TFDO model means it's a graph/saved_model which can directly run on IA platform)

**Comment by hshen14** [comment]
See experimental support: https://github.com/intel/lpot/blob/master/docs/model_conversion.md

**Comment by hshen14** [comment]
Closed this. Please re-open if you have some new requests. Thanks.
