### ISSUE TITLE
ipex quantization model can't be loaded after save

### ISSUE THREAD

**Issue by rnwang04** [intel/neural-compressor#267]
Hi, when I use ipex quantization with inc, I meet a problem that quantized model can't be loaded after save.
When I save, I just call `quantized.save(path)`
and I get a `best_configure.json` under my save dir `tmp_dir`.
Then when I want to load it, I use 
```
from neural_compressor.utils.pytorch import load
from neural_compressor.model.model import PyTorchModel
qmodel = PyTorchModel(load(tmp_dir, model))
```
and I got such error:
```
File "/disk0/miniconda3/envs/ruonan_nano/lib/python3.7/site-packages/bigdl/nano/deps/neural_compressor/pytorch/quantized_model.py", line 52, in _load
    qmodel = PyTorchModel(load(path, model))
  File "/disk0/miniconda3/envs/ruonan_nano/lib/python3.7/site-packages/neural_compressor/utils/pytorch.py", line 165, in load
    stat_dict = torch.load(weights_file)
  File "/disk0/miniconda3/envs/ruonan_nano/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/disk0/miniconda3/envs/ruonan_nano/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/disk0/miniconda3/envs/ruonan_nano/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/disk0/binbin/MSCRED/test/ckpt/ipex_q_model/best_model.pt'
```
which is caused by these code:
![image](https://user-images.githubusercontent.com/105281011/207294846-74d93113-6e64-4bf7-bd41-e953739a1fcb.png)

I think model is not important, the error is irrelevant with model, and you can reproduce it by any model you like.

I wonder if it's a bug of inc, or there is anything I make mistake, like if I should not use` load` function in `neural_compressor.utils.pytorch`.
Are there any special notes on the ipex quantization model, or any corresponding tutorials or instructions?

## version
neural-compressor           1.13.1
torch                       1.12.1

**Comment by changwangss** [comment]
hi, please use the latest version, we not only save the `best_configure.json` but also `best_model.pt` if INC IPEX is used. we recommodate the following method for loading the int8 model now. 
 `load` function. it use the `best_model.pt` to recover, this is a jit model, the detail code is [here](https://github.com/intel/neural-compressor/blob/master/neural_compressor/utils/pytorch.py#L189) 
```
from neural_compressor.utils.pytorch import load
qmodel = load(tmp_dir, model)
```
if you want to use `best_configure.json` to load int8 model, you can refer this [example](https://github.com/intel/neural-compressor/blob/v1.13/examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/run_qa.py#L916).

**Comment by rnwang04** [comment]
Thanks for reply!
I wonder does this fix contains in INC2.0?
When I use INC2.0, it seems this problem still exists that there is no best_model.pt file.

**Comment by changwangss** [comment]
> Thanks for reply! I wonder does this fix contains in INC2.0? When I use INC2.0, it seems this problem still exists that there is no best_model.pt file.

INC will save it automatically if you get the quantized model and call "q_model.save("./saved_results")"
here is the save code: https://github.com/intel/neural-compressor/blob/master/neural_compressor/model/torch_model.py#L778
would you like to share your usage?
