### ISSUE TITLE
How to use this library when doing quantization for Bert via PyTorch

### ISSUE THREAD

**Issue by vgoklani** [intel/neural-compressor#41]
Thank you for releasing this library, unfortunately i'm not sure how to get started.

More specifically, suppose I start with this tutorial:

https://pytorch.org/tutorials/intermediate/dynamic_quantization_bert_tutorial.html

So now I have a quantized BERT model. How do I make it faster using your library? Thanks!

**Comment by ftian1** [comment]
pls be aware that the difference between neural_compressor and native PyTorch quantization API is the former provides accuracy-driven auto tuning mechanism to generate quant config per ops and then get the optimal int8 model. 

You can try to use static quantization to get better performance.

If you want to quantize a NLP model, pls take a look on 
https://github.com/huggingface/optimum/tree/main/examples/pytorch, in which it has integrated neural_compressor as backend and is easy to use

**Comment by chensuyue** [comment]
No feed back in 2 weeks, closed at first. Please reopen if issues still there.
