### ISSUE TITLE
Does INC not support torch.bfloat16 during the pruning process

### ISSUE THREAD

**Issue by tianyil1** [intel/neural-compressor#42]
Hi, when I use the magnitude pruning on models with torch.bfloat16 tensor, if fails:

TypeError: Got unsupported ScalarType BFloat16

I find this error is due to the unsupported operation when converting torch.bfloat16 to numpy array. Why INC does not try to support bfloat16 operation? Is there any special consideration?

**Comment by ftian1** [comment]
thanks for raising such request. yes, currently the magnitude pruning only supports FP32. we will put this under consideration.
