### ISSUE TITLE
Relationship with NNCF?

### ISSUE THREAD

**Issue by nbcsm** [intel/neural-compressor#48]
OpenVINO has NNCF: https://github.com/openvinotoolkit/nncf
There seems to be some feature overlap between INC and NNCF.

Wondering what is the roadmap for these 2 tools? Will they converge?
Thanks.

**Comment by hshen14** [comment]
Thanks for showing your interest. There are multiple differences:
* Product position. INC: inference on **all mainstream frameworks** (TF, PT, ONNX RT, and MXNet); NNCF: inference on **OpenVINO**
* User-facing API. INC: **unified** APIs to support quantization (post-training static/dynamic quantization, training-aware quantization); NNCF: **different** APIs (training-aware quantization in NNCF and post-training quantization in POT)
* Algorithm innovation. INC: block/tile-based structured sparsity; NNCF: some other pruning algorithms

Some algorithms are well known in the industry, so the features built on top of them may look similar. We are encouraging users to understand how these products can help your project first and figure out the best way to use them.

**Comment by ftian1** [comment]
close at first and if there is more questions, we can reopen this issue
