### ISSUE TITLE
INC not installing properly from conda (on a sapphire rapids VM within the Intel Developer Cloud) 

### ISSUE THREAD

**Issue by eduand-alvarez** [intel/neural-compressor#496]
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0

Your installed version is: 2.35

System: Linux cloud31740 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Conda env: 
# packages in environment at /home/ubuntu/miniconda3/envs/idp:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    intel
_openmp_mutex             5.1                       1_gnu    intel
blas                      1.0                         mkl    intel
bzip2                     1.0.8                hb9a14ef_9    intel
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cudatoolkit               11.3.1               h2bc3f7f_2
dpcpp-cpp-rt              2023.0.0            intel_25370    intel
dpcpp_cpp_rt              2023.0.0            intel_25370    intel
fortran_rt                2023.0.0            intel_25370    intel
icc_rt                    2023.0.0            intel_25370    intel
impi_rt                   2021.8.0            intel_25329    intel
intel-cmplr-lib-rt        2023.0.0            intel_25370    intel
intel-cmplr-lic-rt        2023.0.0            intel_25370    intel
intel-fortran-rt          2023.0.0            intel_25370    intel
intel-opencl-rt           2023.0.0            intel_25370    intel
intel-openmp              2023.0.0            intel_25370    intel
intelpython               2023.0.0                      1    intel
intelpython3_core         2023.0.0                 py38_0    intel
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
libblas                   3.9.0           1_h86c2bf4_netlib    conda-forge
libcblas                  3.9.0           5_h92ddd45_netlib    conda-forge
libffi                    3.3                  he6710b0_2    intel
libgcc-ng                 11.2.0               h1234567_1    intel
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   11.2.0               h1234567_1    intel
libstdcxx-ng              11.2.0               h1234567_1    intel
libuv                     1.40.0               h7b6447c_2    intel
mkl                       2023.0.0            intel_25398    intel
mkl-service               2.4.0           py38h3605609_14    intel
mkl_fft                   1.3.1           py38hcab1719_22    intel
mkl_random                1.2.2           py38hbf47bc3_22    intel
mkl_umath                 0.1.1           py38hf66a691_32    intel
ncurses                   6.3                  h5eee18b_3    intel
numpy                     1.22.3           py38hf0956d0_5    intel
numpy-base                1.22.3           py38h45c9ace_5    intel
openssl                   1.1.1q               h7f8727e_0    intel
pip                       22.2.2           py38h06a4308_0    intel
pyeditline                2.0.1                    py38_2    intel
python                    3.8.15               h5cbd770_2    intel
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0              py38h7f8727e_1    intel
readline                  8.2                  h5eee18b_0    intel
scikit-learn              1.0.2            py38h1561384_0    conda-forge
scipy                     1.7.3            py38h55cddf7_6    intel
setuptools                63.4.1           py38h06a4308_0    intel
six                       1.16.0             pyhd3eb1b0_1    intel
sqlite                    3.40.0               h5082296_0    intel
tbb                       2021.8.0            intel_25334    intel
tbb4py                    2021.8.0        py38_intel_25334    intel
tcl                       8.6.10                        2    intel
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h1ccaba5_0    intel
typing_extensions         4.1.1              pyh06a4308_0    intel
wheel                     0.37.1             pyhd3eb1b0_0    intel
xz                        5.2.6                h5eee18b_0    intel
yaml                      0.2.5                h7b6447c_0    intel
zlib                      1.2.13               h5eee18b_0    intel

Machine: 
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         52 bits physical, 57 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Platinum 8480+
    CPU family:          6
    Model:               143
    Thread(s) per core:  1
    Core(s) per socket:  16
    Socket(s):           1
    Stepping:            8
    BogoMIPS:            4000.00
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht
                          syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pn
                         i pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx
                         f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_e
                         nhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpc
                         id avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveo
                         pt xsavec xgetbv1 xsaves avx512_bf16 wbnoinvd arat avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpc
                         lmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid cldemote movdiri movdir64b fsrm md_clear
                         serialize tsxldtrk arch_capabilities
Virtualization features:
  Virtualization:        VT-x
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   512 KiB (16 instances)
  L1i:                   512 KiB (16 instances)
  L2:                    64 MiB (16 instances)
  L3:                    16 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-15
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Unknown: No mitigations
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
  Srbds:                 Not affected
  Tsx async abort:       Not affected

**Comment by chensuyue** [comment]
Hi, are you following the installation guidelines: https://github.com/intel/neural-compressor/blob/master/docs/source/installation_guide.md#install-from-binary, we need 2 channels to gathering all the dependencies.

**Comment by chensuyue** [comment]
Please reopen the issue if there is still issues.
