### ISSUE TITLE
Additional clarifications on AccuracyCriterion

### ISSUE THREAD

**Issue by SimoneMarretta** [intel/neural-compressor#498]
Hello,

I want if possible to have additional clarifications about the usage of AccuracyCriterion. I read the documentation but I couldn't understand it completely.
What is the difference between criterion='relative' and criterion='absolute' and how does this field affect the tolerable_loss field?
Also higher_is_better refers to the output of the eval_func?

Thank you in advance!

**Comment by chensuyue** [comment]
`relative` loss means (int8 acc - fp32 acc)/fp32 acc, and `absolute` loss means int8 acc - fp32 acc. So relative is usually more strict than absolute. `higher_is_better` true or false is based on the metric used to measure the model.

**Comment by SimoneMarretta** [comment]
Thank you!

**Comment by SimoneMarretta** [comment]
Thank you!
