### ISSUE TITLE
PyTorch PTQ does not save model file by default

### ISSUE THREAD

**Issue by ramkrishna1121** [intel/neural-compressor#59]
Post training quantization for PyTorch saves the state file (collections.OrderedDict) instead of the model files.
This prevents conversion to other frameworks like onnx post quantization.
Is there a way to force saving model file?

**Comment by xin3he** [comment]
Hi, @ramkrishna1121, It's a good question, and we also hope it happen.
Unfortunately, for quantized models,  `torch.save/torch.load` is not supported, so we have to use the state dict instead.

For more information, please see https://github.com/pytorch/pytorch/issues/61881

**Comment by chensuyue** [comment]
No feed back in 2 weeks, closed at first.
