### ISSUE TITLE
Magnitude criterion requires abs

### ISSUE THREAD

**Issue by Godofnothing** [intel/neural-compressor#592]
Magnitude pruning prunes weight according to the absolute value of the weight `|w_i|`. The current implementation in 
https://github.com/intel/neural-compressor/blob/master/neural_compressor/compression/pruner/criteria.py takes the weight with sign `w_i` as a score for pruner, therefore large negative weights will be pruned in the first order. However, these weights are quite important and their pruning will change output of the model noticeably. This can be fixed as follows:

```python
    def on_step_begin(self):
        """Calculate and store the pruning scores based on magtinude criterion."""
        with torch.no_grad():
            for key in self.modules.keys():
                p = self.modules[key].weight.data # add .abs() here
                self.scores[key] = p
```

**Comment by chensuyue** [comment]
@YIYANGCAI please follow this issue.
