### ISSUE TITLE
Calibration set in dynamic quantization

### ISSUE THREAD

**Issue by anishagartia** [intel/neural-compressor#60]
https://github.com/intel/neural-compressor/blob/31d3d23bc17e5c4f4973979c9924b80d6be0c571/examples/pytorch/speech_recognition/torchaudio_models/quantization/ptq_dynamic/eager/run_asr.py#L126

This is a dynamic quantization example. Is there need for calibration here? Pls consider removing if not needed.

**Comment by ftian1** [comment]
thanks for reporting that, we will fix it asap and the fix should be in next release

**Comment by chensuyue** [comment]
Fixed in v1.11.
