### ISSUE TITLE
How to enable One-shot Pruning

### ISSUE THREAD

**Issue by Peach-He** [intel/neural-compressor#602]
Hi INC team,

We are intersted in one-shot pruning, is there any examples on how to enable one-shot pruning?

As pruning readme `One-shot pruning means the model is pruned to its target sparsity with one single step. This pruning method often works at model's initialization step. It can easily cause accuracy drop, but save much training time.`, does it mean we don't need training process with one-shot pruning? And for `save much training time`, does it mean one-shot pruning physically reduces model size?

Thanks

**Comment by YIYANGCAI** [comment]
Hi! Thanks for interested in INC! Actually we currently support the schedule of one-shot pruning, just set **start_step=end_step** (please be aware that for gradient based methods including SNIP, SNIP momentum, this step value should be a positive int). You can refer to our [pruner code](https://github.com/intel/neural-compressor/tree/master/neural_compressor/compression/pruner) for more information.

After one-shot pruning process, we still need some further training steps to recover the accuracy.

One-shot pruning actually does not reduce the model size. However, if you apply channel-wise pruning, model size can be reduced and obtain inference acceleration directly by a **model conversion** process. We will release this feature a.s.a.p.

**Comment by chensuyue** [comment]
Closed the issue due to no update for a long time, please re-open the ticket if the issue still there.
