### ISSUE TITLE
When I change the run_benchmark.sh, use different `num_inter_threads` , I get a worse performance?

### ISSUE THREAD

**Issue by GuoGuiRong** [intel/neural-compressor#64]
ENV:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/22836006/159886454-697d1a2d-1609-4931-83d7-03f98e4acd6c.png">

Test result:
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/22836006/159903474-36e7bc91-e575-4859-988f-605fd342f847.png">

**Comment by ftian1** [comment]
yes, some models get impacted by this inter_num significantly. this parameter is used to control how many parallel processes are used to execute irrelevant ops in the graph. for those models which have many parallel branches, a bigger inter_num will bring the faster inference speed

**Comment by chensuyue** [comment]
No feed back in 2 weeks, closed at first.
