### ISSUE TITLE
Failed to import neural compressor ( No response when import )

### ISSUE THREAD

**Issue by donny8** [intel/neural-compressor#646]
I installed the neural-compressor through pip.
I could check it was installed successfully by checking the pip freeze as follows : 
<img width="201" alt="image" src="https://user-images.githubusercontent.com/55653250/224634056-3dbcdab4-5511-4900-8ee8-4b1f6478fd7f.png">

Then, I tried to follow the examples, but I ended up to wait at least 10 minutes to import any module.
It did not mean that it took 10 minute to import any module, but stay still without any response like the figure below.
I just had to kill the process after 10 minutes waiting.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/55653250/224634595-6a9d3e9e-350d-4282-8e9a-c768cc9aee99.png">

I'm using python 3.9.16 on Windows10 and executed the command in an anaconda environment.
Would you please tell me what should I do?

**Comment by chensuyue** [comment]
Hi, I try to reproduce your issue on the same env, but I didn't meet this issue. Have you met the same import issue with other components or just neural-compressor? 
![image](https://user-images.githubusercontent.com/51692656/224772046-37d0a80f-12c0-4e79-9a43-4097231a4119.png)

**Comment by donny8** [comment]
First of all, thank you for your help.
Importing other package was successfully done as below.
![image](https://user-images.githubusercontent.com/55653250/224871344-8aa92ed6-d36c-498b-843b-13cd514e25fc.png)
I tried the same thing on Linux, and it worked fine then.
I guess it was WIndows or other environment that caused problem.
Once again, thank you
