### ISSUE TITLE
TfServing is not Support neural-compressor directly, If I need to use docker build from Tfserving source code?

### ISSUE THREAD

**Issue by GuoGuiRong** [intel/neural-compressor#67]
I want to run a PTQ model in tferving, but Tfserving not support directly,  If I need to use docker build from Tfserving source code?
my env:
tensorflow 2.7
tfserving 2.7.0-gpu

**Comment by ftian1** [comment]
we didn't evaluate such feature. will have a look on that. thanks for the feedback

**Comment by chensuyue** [comment]
No feed back in 2 weeks, closed at first.
