### ISSUE TITLE
Support to convert the text-to-image quantized stable diffusion models to onnx 

### ISSUE THREAD

**Issue by sravanthOppo27** [intel/neural-compressor#842]
Dear Author , I am able to convert the FP32 stable diffusion model to INT8 quantized model 
But I haven't seen any support functions / api's for converting quantized INT8 SD model to onnx .
When can we expect the support for it

**Comment by chensuyue** [comment]
Hi, I see some similar discussion under https://github.com/intel/neural-compressor/issues/87, do you still have the issue?

**Comment by sravanthOppo27** [comment]
Yes , torch2onnx.py supports other models not the stable diffusion models 
I am not able to convert the model

**Comment by xin3he** [comment]
Hi @sravanthOppo27 Please split stable diffusion model and convert them one-by-one.

**Comment by chensuyue** [comment]
Closed the issue due to no update for a long time, please re-open the ticket if the issue still there.
