### ISSUE TITLE
import quantized pytorch model and export into quantized onnx ones

### ISSUE THREAD

**Issue by davidegiaca** [intel/neural-compressor#87]
Hello,

I'd like to know if INC is able to load quantized pytorch models and export it into a quantized onnx model.

Thanks

**Comment by hshen14** [comment]
Thanks @davidegiaca for reporting. This feature was being developed. May I know what's the source model, TensorFlow or PyTorch?

**Comment by xin3he** [comment]
@davidegiaca Please refer to this link and try it out. we have not yet prepared a documentation for this feature, you can expect it in the next release.
https://github.com/intel-innersource/frameworks.ai.lpot.intel-lpot/blob/master/test/test_torch2onnx.py
Note: please use nightly install for the latest feature, thanks.

**Comment by davidegiaca** [comment]
> Thanks @davidegiaca for reporting. This feature was being developed. May I know what's the source model, TensorFlow or PyTorch? cc @xin3he

Thanks for your reply. 
I'm using a quantized pytorch model

**Comment by davidegiaca** [comment]
> @davidegiaca Please refer to this link and try it out. we have not yet prepared a documentation for this feature, you can expect it in the next release. https://github.com/intel/neural-compressor/blob/master/test/test_torch2onnx.py Note: please use nightly install for the latest feature, thanks.

Thank you,
I'll try it

**Comment by sravanthOppo27** [comment]
Does the torch2onnx.py file have support to convert quantized stable diffusion model to onnx format

**Comment by xin3he** [comment]
Stable diffusion is a combination of CV and NLP models, you can export them one-by one and combine them back.

**Comment by sravanthOppo27** [comment]
I have onyl quantized unet part of Stable diffusion model , I want only that part to onnx .
