### ISSUE TITLE
Cannot find path for downloading training data

### ISSUE THREAD

**Issue by ChiragNayak7007** [intel/neural-compressor#88]
Need to know the path were downloaded data is getting stored after downloading for training...

**Comment by chensuyue** [comment]
Which case do you mention?

**Comment by ChiragNayak7007** [comment]
When I am running main.py in path **"intel/neural-compressor/tree/master/examples/tensorflow/image_recognition/inception_v3/pruning/magnitude"** I am getting error:-

raise valueerror ('Found no files in --root matching: {}'.format(glob_pattern))

**Comment by hshen14** [comment]
cc @VincyZhang

**Comment by VincyZhang** [comment]
Hi @ChiragNayak7007 
       Could you please provide more detailed info, such as your env, INC version, more error log...... since I can't reproduce your problem. 
       And please check if you have modified yaml to fit with your own path of datasets before running.
       https://github.com/intel/neural-compressor/blob/master/examples/tensorflow/image_recognition/inception_v3/pruning/magnitude/prune_inception_v3.yaml#L26
       https://github.com/intel/neural-compressor/blob/master/examples/tensorflow/image_recognition/inception_v3/pruning/magnitude/prune_inception_v3.yaml#L67
      Maybe this will work for you!

**Comment by chensuyue** [comment]
Closed since no new feedback for 1 week, please reopen if the issue still there.
