### ISSUE TITLE
error: rsa 4.8 is installed but rsa<4.6; python_version < "3.6" is required by {'google-auth'}

### ISSUE THREAD

**Issue by alemorcuq** [intel/neural-compressor#91]
I've got the following error when building INC 1.12 with TF 2.9.1 and Python 3.10:

```
[...]

$ python setup.py install

[...]

neural_compressor.ux.components.optimization.graph_optimizer.__pycache__.graph_optimization.cpython-310: module references __file__
neural_compressor.ux.components.optimization.tune.__pycache__.tuning.cpython-310: module references __file__
neural_compressor.ux.components.profiling.__pycache__.profiling.cpython-310: module references __file__
neural_compressor.ux.utils.__pycache__.environment.cpython-310: module references __file__
neural_compressor.ux.utils.__pycache__.utils.cpython-310: module references __file__
zip_safe flag not set; analyzing archive contents...
backports.__pycache__.__init__.cpython-310: module references __path__
error: rsa 4.8 is installed but rsa<4.6; python_version < "3.6" is required by {'google-auth'}
```

**Steps I followed:**

1. Clone the repository, checkout tag v1.12 and init submodules.
2. Install TensorFlow with `pip install tensorflow`
3. Install INC's requirements with `pip install -r requirements.txt`
4. Install INC with `python setup.py install`. This last command throws the error shown above.

Python version: 3.10.4

Using Python 3.9 instead the above procedure works without issue.

**Comment by hshen14** [comment]
Thanks for reporting the issue. cc @chensuyue

**Comment by chensuyue** [comment]
Hi @alemorcuq 
I try those install steps in 2 difference machines, both works well.   
Just wondering whether there is an old `google-auth` cache in your machine.  
```
(test-py310) tensorflow@aipg-ra-clx-22:~/suyue/neural-compressor$ pip list | grep rsa
rsa                          4.8
(test-py310) tensorflow@aipg-ra-clx-22:~/suyue/neural-compressor$ pip list | grep google-auth
google-auth                  2.9.0
google-auth-oauthlib         0.4.6
```

And have you try `pip install neural-compressor`, does it work for you?

**Comment by chensuyue** [comment]
Closed since no new feedback for 1 week, please reopen if the issue still there.
