### ISSUE TITLE
can pytorch adaptor enable list input ?

### ISSUE THREAD

**Issue by rnwang04** [intel/neural-compressor#92]
Hi, when I use neural-compressor, I meet a problem.
Here is part of my model forward function: 
`transfomer_features, user_features, target_movie_rating = self.encode_input(batch)`
and the batch is a sequence of length 9.
error is from this line:
https://github.com/rnwang04/neural-compressor/blob/16a4a12045fcb468da4d33769aff2c1a5e2ba6ba/neural_compressor/adaptor/pytorch.py#L108
In my case, I modify it as :
```
try:
    output = model(*input)
except:
    output = model(input)
```
then it works.
So is it possible for you to enable the two types of input?

**Comment by xin3he** [comment]
@rnwang04  How about using 'batch = [batch]' to wrap input? 
Is it easy to enable it on your part? If not, we will take your suggestion into consideration, thanks.

**Comment by rnwang04** [comment]
Oh it works. Thanks for your advice!
