### ISSUE TITLE
Framework is not detected correctly from model format

### ISSUE THREAD

**Issue by Charles-258** [intel/neural-compressor#94]
The imput model format is onnx, and the framework onnxruntime can not detect the model format.

**Comment by mengniwang95** [comment]
Hi, could you provide your launcher codes and installed pkg to help locate problems?

**Comment by Charles-258** [comment]
> Hi, could you provide your launcher codes and installed pkg to help locate problems?

Here is the link of code and data: https://drive.google.com/file/d/1ep0jKgnodvN8mL1E6Fsr08B2T5qCkX46/view?usp=sharing
and thanks for your help.

**Comment by mengniwang95** [comment]
Do you install onnxruntime-extensions?

**Comment by Charles-258** [comment]
> Do you install onnxruntime-extensions?

I have just install this package, but it still cant  get the proper quantitized model.

**Comment by mengniwang95** [comment]
Sorry for my late reply, could you paste your error info? I try your script and it shows INC can detect model correctly but the input format is incorrect.
![image](https://user-images.githubusercontent.com/65003808/180907828-6b89dada-31ae-4aa8-b5c9-5911e46f9395.png)

**Comment by Charles-258** [comment]
Here is my error info. Thanks for your help.
![QQ图片20220727133140](https://user-images.githubusercontent.com/68986816/181168713-3d64ffe9-0ee8-48e4-a125-d07e3593c756.png)

**Comment by mengniwang95** [comment]
This bug is caused by inference time collection. Since you don't provide eval_func or eval_dataloader+metric, it generates a fake eval_func automatically and it seems to jump in and jump out this eval_func at the same time... 
you can change line137 of objective.py to self.duration >= 0 locally to fix this problem and we will fix it in next release.
