### ISSUE TITLE
torch.nn.MultiheadAttention module support in Smoothquant

### ISSUE THREAD

**Issue by maktukmak** [intel/neural-compressor#960]
torch.nn.MultiheadAttention module is currently not fully supported by INC Smoothquant feature neither when folding is True nor False.  This module has multiple linear layers that need to be quantized properly.

When folding is True, INC detects linear layers in torch.nn.MultiheadAttention module but can't apply smoothquant transform so quantization is done without the transform. When folding is False, INC can't even detect linears in torch.nn.MultiheadAttention module, so it completely skips quantization for these linear layers.

Expected behavior is that linear layers in torch.nn.MultiheadAttention module should be quantized properly with Smoothquant transform when both folding is False and True. torch.nn.MultiheadAttention occurs in the BridgeTower model, which is the model I am currently trying to quantize.

**Comment by hshen14** [comment]
@chensuyue Please confirm whether the fixing was included in v2.2 release. If so, we can close the issue with the description.

**Comment by chensuyue** [comment]
Hi @maktukmak we don't have the plan to support torch.nn.MultiheadAttention module in Smoothquant for now.

**Comment by chensuyue** [comment]
Closed the issue due to no update for a long time, please re-open the ticket if the issue still there.
