### ISSUE TITLE
it's not reasonable to deepcopy a model before sq

### ISSUE THREAD

**Issue by wenhuach21** [intel/neural-compressor#986]
[WARNING] Smoothquant for ipex requires a deepcopy of model, please avoid out of memory.

**Comment by ftian1** [comment]
smooth_quant is just a recipe, INC strategy needs to tune it (enable or disable). we can't enable Smooth_Quant at the beginning of tuning unless we prove its generalization on all models.

**Comment by wenhuach21** [comment]
Yes, however, we need to fix the deep copy issue.  I don't know why we need a deepcopy before applying sq. If there are some issues for some models, I prefer to skip sq for these models rather than add a common deepcopy

**Comment by wenhuach21** [comment]
smooth quant itself is a in-place operation and has offered a recover function to revert the change

**Comment by hshen14** [comment]
If we are talking about IPEX backend, it's a current limitation by IPEX since their API changes the model after prepare. We submitted an issue to IPEX team. For the other backends, generally agree that we should not have deepcopy.

**Comment by chensuyue** [comment]
Closed the issue due to no update for a long time, please re-open the ticket if the issue still there.
