### ISSUE TITLE
memory leak of quantization

### ISSUE THREAD

**Issue by wenhuach21** [intel/neural-compressor#987]
https://github.com/intel/intel-extension-for-transformers/blob/main/examples/huggingface/pytorch/language-modeling/quantization/run_clm_no_trainer.py
Following this example, when I change the code to the following, clear memory leak behaviour is observed after sq is done

    if args.sq:
        from neural_compressor.adaptor.torch_utils.smooth_quant import TorchSmoothQuant
        sq = TorchSmoothQuant(user_model,dataloader=calib_dataloader)
        args.alpha = args.alpha if args.alpha == "auto" else float(args.alpha)
        sq.transform(args.alpha, folding=True)
        print("sq done",flush=True)
        recipes = {"smooth_quant": True, "smooth_quant_args": {'alpha': args.alpha}}
        conf = PostTrainingQuantConfig(
            backend="ipex" if args.ipex else "default",
            excluded_precisions=excluded_precisions,
            op_type_dict=op_type_dict,
            #recipes=recipes,
        )

**Comment by xin3he** [comment]
We have refactored our SQ structure, please have a try. Thanks.
https://github.com/intel/neural-compressor/pull/1109
