### ISSUE TITLE
Quantizing model in per-tensor way does't work

### ISSUE THREAD

**Issue by WanliZhong** [intel/neural-compressor#99]
Hi, I try to quantize all the parameters of my model in a per_tensor way. But the result shows that there are still some layers not in per_tensor way as below image shown.
![image](https://user-images.githubusercontent.com/49567307/185093276-448eee73-b4d7-4462-a3e1-f6bf6b560180.png)

The config file is following:

```shell

version: 1.0

model:                                               # mandatory. used to specify model specific information.
  name: mp_handpose
  framework: onnxrt_qlinearops                       # mandatory. supported values are tensorflow, pytorch, pytorch_ipex, onnxrt_integer, onnxrt_qlinear or mxnet; allow new framework backend extension.

quantization:                                        # optional. tuning constraints on model-wise for advance user to reduce tuning space.
  approach: post_training_static_quant               # optional. default value is post_training_static_quant.                          
  calibration:
    dataloader:
      batch_size: 1
      dataset:
        dummy:
          shape: [1, 256, 256, 3]
          low: -1.0
          high: 1.0
          dtype: float32
          label: True

  model_wise:                                        # optional. tuning constraints on model-wise for advance user to reduce tuning space.
    weight:
      granularity: per_tensor
      scheme: asym
      dtype: int8
      algorithm: minmax
    activation:
      granularity: per_tensor
      scheme: asym
      dtype: int8, fp32
      algorithm: minmax, kl

tuning:
  accuracy_criterion:
    relative:  0.02                                  # optional. default value is relative, other value is absolute. this example allows relative accuracy loss: 1%.
  exit_policy:
    timeout: 0                                       # optional. tuning timeout (seconds). default value is 0 which means early stop. combine with max_trials field to decide when to exit.
  random_seed: 9527                                  # optional. random seed for deterministic tuning.

```

The model I use is https://github.com/WanliZhong/opencv_zoo/blob/handpose_tracker/models/handpose_estimation_mediapipe/handpose_estimation_mediapipe_2022may.onnx

Thanks!

**Comment by mengniwang95** [comment]
Hi, I try it on my local env and this is the result:
![image](https://user-images.githubusercontent.com/65003808/185107804-706f65f4-a0e8-42f4-9d79-7184594377c9.png)

please try
'''yaml
  model_wise:                                        # optional. tuning constraints on model-wise for advance user to reduce tuning space.
    weight:
      granularity: per_tensor
      scheme: asym
      dtype: int8
      algorithm: minmax
    activation:
      granularity: per_tensor
      scheme: asym
      dtype: int8
      algorithm: minmax
```
